apiVersion: apps/v1
kind: Deployment
metadata:
  name: openapi-swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openapi-swagger
  template:
    metadata:
      labels:
        app: openapi-swagger
    spec:
      containers:
      - name: openapi-swagger
        image: evilpuppet/openapi-swagger:latest
        ports:
        - containerPort: 8080  # Ensure this matches the Quarkus application
